// <auto-generated />
using System;
using EducationApp.Data.Concrete.EFCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducationApp.Data.Migrations
{
    [DbContext(typeof(EducationAppContext))]
    [Migration("20230729193301_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("EducationApp.Entity.Concrete.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 468, DateTimeKind.Local).AddTicks(6767),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 468, DateTimeKind.Local).AddTicks(6780),
                            UserId = "956fdfef-d0e5-46e7-9412-52ef94d80fba"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 468, DateTimeKind.Local).AddTicks(6786),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 468, DateTimeKind.Local).AddTicks(6786),
                            UserId = "0165042f-4675-45d9-837c-116cd53c458a"
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1719),
                            Description = "Yazılım geliştirme, bilgisayar programlarının tasarımı, oluşturulması ve sürdürülmesi sürecidir. Bu süreç, kullanıcı ihtiyaçlarını karşılamak, işlevsellik sağlamak ve teknolojik çözümler üretmek için kodlama, test etme ve dağıtma adımlarını içerir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1727),
                            Name = "Yazılım Geliştime",
                            Url = "yazilim-gelistirme"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1731),
                            Description = "Mobil uygulama geliştirme, mobil platformlarda çalışabilen kullanışlı ve etkileşimli yazılım uygulamalarının tasarımı, oluşturulması ve dağıtılması sürecidir. Bu süreç, kullanıcı ihtiyaçlarını karşılamak, sorunlara çözüm sunmak ve kullanıcı deneyimini geliştirmek için programlama, arayüz tasarımı, test etme ve dağıtma adımlarını içerir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1731),
                            Name = "Mobil Uygulama Geliştirme",
                            Url = "mobil-uygulama-gelistirme"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1754),
                            Description = "Oyun geliştirme, video oyunlarının tasarımı, programlaması ve oluşturulması sürecidir. Bu süreç, oyun kavramının belirlenmesi, hikaye yazımı, karakter tasarımı, dünya oluşturma, grafik ve ses tasarımı, oyun mekaniği ve kullanıcı arayüzü gibi aşamaları içerir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1755),
                            Name = "Oyun Geliştime",
                            Url = "oyun-gelistirme"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1756),
                            Description = "Web, dünya genelinde bilgilere erişim sağlayan ve kullanıcıların çeşitli hizmetlere bağlanmasını mümkün kılan bir ağdır. Web, HTML, CSS ve JavaScript gibi teknolojilerle oluşturulan web siteleri ve web uygulamaları aracılığıyla çalışır.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1756),
                            Name = "Web",
                            Url = "web"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1757),
                            Description = "Veritabanı, yapılandırılmış verilerin depolandığı ve yönetildiği bir elektronik sistemdir. Veritabanları, bilgiyi organize etmek, erişmek, güncellemek ve analiz etmek için kullanılır. İşletmeler, kuruluşlar ve web uygulamaları gibi birçok alan veritabanlarını kullanır.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1757),
                            Name = "Veritabanı",
                            Url = "veritabani"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1758),
                            Description = "DevOps, yazılım geliştirme ve işletim süreçlerini birleştirerek, yazılım projelerinin daha hızlı, güvenilir ve sürekli bir şekilde dağıtılmasını sağlayan bir yaklaşımdır. Bu metodoloji, geliştirme (Development) ve işletim (Operations) ekipleri arasında işbirliği ve iletişimi teşvik eder.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1758),
                            Name = "DevOps",
                            Url = "devops"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1759),
                            Description = "Bulut, internet üzerinde sunulan paylaşımlı bilgi işlem kaynaklarını ifade eder. Bulut hizmetleri, sunucular, depolama, veritabanları, ağ altyapısı ve uygulama hizmetleri gibi kaynaklara erişimi kolaylaştırır. Kullanıcılar, istedikleri zaman istedikleri yerden bu kaynaklara güvenli bir şekilde erişebilir ve ihtiyaçlarına göre ölçeklendirebilir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(1759),
                            Name = "Bulut",
                            Url = "bulut"
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("BirthOfYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId1");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1990,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4295),
                            FirstName = "Dominic",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Harmon",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4300),
                            PhotoUrl = "1.png",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1990,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4307),
                            FirstName = "Justina",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Burch",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4307),
                            PhotoUrl = "1.png",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1985,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4309),
                            FirstName = "Madison",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Beard",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4309),
                            PhotoUrl = "1.png",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1982,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4310),
                            FirstName = "Sara",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Wade",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4310),
                            PhotoUrl = "1.png",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1988,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4312),
                            FirstName = "Jacob",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hunt",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4312),
                            PhotoUrl = "1.png",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1989,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4313),
                            FirstName = "Osamu",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dazai",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4313),
                            PhotoUrl = "1.png",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1983,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4315),
                            FirstName = "Zachery",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Salas",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4315),
                            PhotoUrl = "1.png",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1982,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4316),
                            FirstName = "Matt",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Haig",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4316),
                            PhotoUrl = "1.png",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1982,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4317),
                            FirstName = "William",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hawkingan",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4318),
                            PhotoUrl = "1.png",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1990,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4319),
                            FirstName = "Geraldine",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Richmond",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4319),
                            PhotoUrl = "1.png",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1983,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4320),
                            FirstName = "Steffan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Ros",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4321),
                            PhotoUrl = "1.png",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1991,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4322),
                            FirstName = "Nichole",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Talley",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4322),
                            PhotoUrl = "1.png",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1979,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4323),
                            FirstName = "Yetta",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Sheppard",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4324),
                            PhotoUrl = "1.png",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1978,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4325),
                            FirstName = "Elijah",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Farley",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4325),
                            PhotoUrl = "1.png",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 15,
                            About = "Yazılım eğitimi, modern teknolojinin temelini oluşturan önemli bir süreçtir. Katılımcılara yazılım geliştirme süreçlerinde bilgi ve beceriler kazandırır.",
                            BirthOfYear = 1991,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4326),
                            FirstName = "Neil",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Wooten",
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 469, DateTimeKind.Local).AddTicks(4326),
                            PhotoUrl = "1.png",
                            ProductId = 15
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9522),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "1.jpg",
                            InstructorId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9526),
                            Name = ".NET (.NET Core, MVC, Web API)",
                            Price = 100m,
                            Time = 200,
                            Url = ".net-core-mvc"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9531),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "2.jpg",
                            InstructorId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9531),
                            Name = "Java (Spring, Java SE, Java EE)",
                            Price = 100m,
                            Time = 200,
                            Url = "java"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9533),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "3.png",
                            InstructorId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9534),
                            Name = "Python",
                            Price = 100m,
                            Time = 200,
                            Url = "python"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9535),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "4.jpeg",
                            InstructorId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9536),
                            Name = "JavaScript",
                            Price = 100m,
                            Time = 200,
                            Url = "javascript"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9537),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "5.jpg",
                            InstructorId = 5,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9538),
                            Name = "C/C++",
                            Price = 100m,
                            Time = 200,
                            Url = "c/c++	"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9540),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "6.png",
                            InstructorId = 6,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9540),
                            Name = "iOS & Android",
                            Price = 100m,
                            Time = 200,
                            Url = "ios-android"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9542),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "7.png",
                            InstructorId = 7,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9542),
                            Name = "React Native",
                            Price = 100m,
                            Time = 200,
                            Url = "react-native"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9544),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "8.png",
                            InstructorId = 8,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9544),
                            Name = "Flutter",
                            Price = 100m,
                            Time = 200,
                            Url = "flutter"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9545),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "9.jpg",
                            InstructorId = 9,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9546),
                            Name = "Ionic",
                            Price = 100m,
                            Time = 200,
                            Url = "ionic"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9547),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "10.jpeg",
                            InstructorId = 10,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9547),
                            Name = "Unity",
                            Price = 100m,
                            Time = 200,
                            Url = "unity"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9549),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "11.png",
                            InstructorId = 11,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9549),
                            Name = "Unreal Engine",
                            Price = 100m,
                            Time = 200,
                            Url = "unreal-engine"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9551),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "12.png",
                            InstructorId = 12,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9551),
                            Name = "GameMaker Studio",
                            Price = 100m,
                            Time = 200,
                            Url = "gamemaker-studio"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9552),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "13.jpeg",
                            InstructorId = 13,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9553),
                            Name = "Buildbox",
                            Price = 100m,
                            Time = 200,
                            Url = "buildbox"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9554),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "14.png",
                            InstructorId = 14,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9554),
                            Name = "PHP",
                            Price = 100m,
                            Time = 200,
                            Url = "php"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9556),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "15.jpeg",
                            InstructorId = 8,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9556),
                            Name = "React",
                            Price = 100m,
                            Time = 200,
                            Url = "react"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9558),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "16.png",
                            InstructorId = 9,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9558),
                            Name = "Angular",
                            Price = 100m,
                            Time = 200,
                            Url = "angular"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9560),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "17.png",
                            InstructorId = 10,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9561),
                            Name = "Node.js",
                            Price = 100m,
                            Time = 200,
                            Url = "nodejs"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9562),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "18.jpg",
                            InstructorId = 11,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9562),
                            Name = "Microsoft SQL Server",
                            Price = 100m,
                            Time = 200,
                            Url = "microsoft-sql-server"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9564),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "19.png",
                            InstructorId = 12,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9564),
                            Name = "MySQL",
                            Price = 100m,
                            Time = 200,
                            Url = "mysql"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9565),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "20.png",
                            InstructorId = 13,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9566),
                            Name = "PostgreSQL",
                            Price = 100m,
                            Time = 200,
                            Url = "postgresql"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9567),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "21.png",
                            InstructorId = 11,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9567),
                            Name = "SQLite",
                            Price = 100m,
                            Time = 200,
                            Url = "sqlite"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9569),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "22.png",
                            InstructorId = 12,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9569),
                            Name = "Oracle",
                            Price = 100m,
                            Time = 200,
                            Url = "oracle"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9570),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "23.png",
                            InstructorId = 13,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9571),
                            Name = "Docker",
                            Price = 100m,
                            Time = 200,
                            Url = "docker"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9572),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "24.png",
                            InstructorId = 14,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9572),
                            Name = "Jenkins",
                            Price = 100m,
                            Time = 200,
                            Url = "jenkins"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9574),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "25.png",
                            InstructorId = 8,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9574),
                            Name = "Ansible",
                            Price = 100m,
                            Time = 200,
                            Url = "ansible"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9575),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "26.jpeg",
                            InstructorId = 9,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9576),
                            Name = "Sonarcube",
                            Price = 100m,
                            Time = 200,
                            Url = "sonarcube"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9577),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "27.png",
                            InstructorId = 10,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9577),
                            Name = "AWS",
                            Price = 100m,
                            Time = 200,
                            Url = "aws"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9579),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "28.png",
                            InstructorId = 11,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9579),
                            Name = "Azure",
                            Price = 100m,
                            Time = 200,
                            Url = "azure"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9581),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "29.png",
                            InstructorId = 12,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9581),
                            Name = "Serverless",
                            Price = 100m,
                            Time = 200,
                            Url = "serverless"
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9583),
                            Description = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                            ImageUrl = "30.png",
                            InstructorId = 12,
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 7, 29, 22, 33, 1, 470, DateTimeKind.Local).AddTicks(9583),
                            Name = "Cloud Storage",
                            Price = 100m,
                            Time = 200,
                            Url = "cloudstorage"
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 7
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d2f08f00-eb4f-49da-b8bd-5b0275dc44f9",
                            Description = "Yöneticilerin rolü bu.",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "aabace03-8a96-4fa7-94b9-da29dff0f44b",
                            Description = "Diğer tüm kullanıcıların rolü bu.",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "956fdfef-d0e5-46e7-9412-52ef94d80fba",
                            AccessFailedCount = 0,
                            Address = "Ferit Sidal Sk. No:12 D:56 Yenibosna",
                            City = "İstanbul",
                            ConcurrencyStamp = "25e0425f-5c3d-4e5e-b088-f95d3061dcbc",
                            DateOfBirth = new DateTime(1995, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "serkanselek34@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Serkan",
                            Gender = "ERKEK",
                            LastName = "Selek",
                            LockoutEnabled = true,
                            Name = " ",
                            NormalizedEmail = "SERKANSELEK34@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEOFRu22wPRAKGZULrg6LvPJQkJfwjpquIFfiEJ/YwtFJ9vT2wPYX+FSMu+VcWxp4Kw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "0165042f-4675-45d9-837c-116cd53c458a",
                            AccessFailedCount = 0,
                            Address = "Göztepe Mh. 2366 Sk. No:7 D:56 Bağcılar",
                            City = "İstanbul",
                            ConcurrencyStamp = "0e391bc6-406d-4950-a571-7a0259459d45",
                            DateOfBirth = new DateTime(1995, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "onrustaoglu@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Onur",
                            Gender = "ERKEK",
                            LastName = "Ustaoğlu",
                            LockoutEnabled = true,
                            Name = " ",
                            NormalizedEmail = "ONRUSTAOGLU@GMAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEMBCcCxob6nIehab6pz1m7xSZKA7QgpEa7ObfzITi+9lF3/6ev//NNWW+DhaBVQTWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "956fdfef-d0e5-46e7-9412-52ef94d80fba",
                            RoleId = "d2f08f00-eb4f-49da-b8bd-5b0275dc44f9"
                        },
                        new
                        {
                            UserId = "0165042f-4675-45d9-837c-116cd53c458a",
                            RoleId = "aabace03-8a96-4fa7-94b9-da29dff0f44b"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Cart", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.CartItem", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationApp.Entity.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Instructor", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Order", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.OrderItem", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationApp.Entity.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Product", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Instructor", "Instructor")
                        .WithMany("Products")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.ProductCategory", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationApp.Entity.Concrete.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EducationApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Instructor", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EducationApp.Entity.Concrete.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
